import { ArrowRight, Building2, Car, CreditCard, FolderOpen, Pencil, PhoneCall, ShipWheel, Sparkles } from 'lucide-react'
const iconByType = { dossier: FolderOpen, maritime: ShipWheel, finance: CreditCard, telecom: PhoneCall, corporate: Building2, vehicle: Car }
const riskClass = { High: 'bg-[#fbeaea] text-[#c0362c]', Medium: 'bg-[#f4ead8] text-[#8d6117]', Low: 'bg-[#ece8e1] text-[#5b564b]' }
const statusFilters = new Set(['Active', 'Cold', 'Closed'])
export function CaseDirectory({ cases, filter, onSelect, onEdit, justAddedId }) {
  const filtered = cases.filter((item) => {
    if (filter === 'High Risk Only') return item.risk === 'High'
    if (statusFilters.has(filter)) return item.status === filter
    return true
  })
  return <div className="overflow-hidden rounded-xl border border-[#e5e0d8] bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[920px] border-collapse text-left"><thead className="bg-[#faf7f2] font-mono text-[10px] uppercase tracking-wider text-[#8a8578]"><tr><th className="w-12 px-4 py-3 text-center">Type</th><th className="px-4 py-3">Case ID & dossier title</th><th className="px-4 py-3">Primary target / subject</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Risk rating</th><th className="px-4 py-3">Lead investigator</th><th className="px-4 py-3">Last logged</th><th className="w-20 px-4 py-3" /></tr></thead><tbody className="divide-y divide-[#e5e0d8] text-[13px]">{filtered.length === 0 && <tr><td colSpan={8} className="px-4 py-8 text-center text-sm text-[#8a8578]">No cases match this filter.</td></tr>}{filtered.map((item) => { const Icon = iconByType[item.type] || FolderOpen; const isNew = item.id === justAddedId; return <tr className={`group cursor-pointer transition hover:bg-[#faf7f2] ${isNew ? 'bg-[#f4ead8]' : ''}`} key={item.id} onClick={() => onSelect(item)}><td className="px-4 py-4 text-center text-[#777166]"><Icon className="mx-auto size-[18px]" /></td><td className="px-4 py-4"><p className="font-mono text-[10px] text-[#8a8578]">{item.id}</p><p className="mt-1 flex items-center gap-2 font-semibold group-hover:underline">{item.title}{isNew && <span className="rounded-full bg-[#c08a2e] px-1.5 py-0.5 font-mono text-[9px] font-semibold uppercase tracking-wider text-white">New</span>}</p></td><td className="px-4 py-4"><span className="font-medium">{item.subject}</span>{item.alias && <span className="ml-2 font-mono text-[11px] text-[#8a8578]">({item.alias})</span>}{item.ai && <Sparkles className="ml-1.5 inline size-3 text-[#c08a2e]" />}</td><td className="px-4 py-4"><span className="rounded-full border border-[#e5e0d8] px-2 py-1 text-[11px]">{item.status}</span></td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 text-[11px] font-semibold ${riskClass[item.risk]}`}>{item.risk} Risk</span></td><td className="px-4 py-4 text-[#777166]">{item.lead}</td><td className="px-4 py-4 font-mono text-[11px] text-[#777166]">{item.updated}</td><td className="px-4 py-4"><div className="flex items-center justify-end gap-2">{onEdit && <button title="Edit case" onClick={(event) => { event.stopPropagation(); onEdit(item) }} className="rounded-full p-1.5 text-[#8a8578] transition hover:bg-[#ece8e1] hover:text-[#171511]"><Pencil className="size-[15px]" /></button>}<ArrowRight className="size-[17px] text-[#8a8578] transition group-hover:translate-x-1 group-hover:text-[#171511]" /></div></td></tr> })}</tbody></table></div></div>
}
