import { BellRing, FileText, FolderOpen, LayoutDashboard, Radar, Search, Settings2, ShieldCheck } from 'lucide-react'
import { alertSeed } from '../dashboardData'
import { BrandMark } from './BrandMark'
const links = [['Dashboard', LayoutDashboard], ['Cases', FolderOpen], ['Case Graph', ShieldCheck], ['Intelligence', Radar], ['Network Search', Search], ['Alerts', BellRing], ['Reports', FileText], ['Admin', Settings2]]
const unbuilt = new Set(['Reports', 'Admin'])
export function DashboardSidebar({ active, onNavigate }) {
  function go(name) { if (unbuilt.has(name)) return; onNavigate(name) }
  return <aside className="flex w-full shrink-0 flex-col justify-between border-b border-[#e5e0d8] bg-[#f5f1ea] md:fixed md:inset-y-0 md:left-0 md:w-60 md:border-b-0 md:border-r"><div><div className="border-b border-[#e5e0d8] px-5 py-5"><div className="flex items-center gap-2"><BrandMark compact /><div><p className="text-[13px] font-semibold uppercase tracking-wider">Nexus // Intel</p><p className="font-mono text-[10px] tracking-widest text-[#8a8578]">Investigations</p></div></div><span className="mt-3 inline-flex items-center gap-2 rounded border border-[#d4cebf] bg-[#faf7f2] px-2 py-1 font-mono text-[10px] tracking-wide text-[#6e685c]"><i className="size-1.5 rounded-full bg-[#c08a2e]"/> SECURE PORTAL // LNX-9402</span></div><nav className="flex gap-1 overflow-x-auto px-3 py-4 md:flex-col">{links.map(([name, Icon]) => { const disabled = unbuilt.has(name); return <button key={name} onClick={() => go(name)} disabled={disabled} aria-disabled={disabled} title={disabled ? `${name} is not built yet` : undefined} className={`flex shrink-0 items-center gap-3 rounded-full px-3 py-2 text-left text-[13px] font-medium transition ${disabled ? 'cursor-not-allowed text-[#b3ac9c]' : active === name ? 'bg-[#111] text-white' : 'text-[#777166] hover:bg-[#ece8e1] hover:text-[#171511]'}`}><Icon className="size-[18px]"/>{name}{name === 'Alerts' && <span className="ml-auto rounded-full bg-[#fbeaea] px-1.5 py-0.5 text-[10px] text-[#c0362c]">{alertSeed.length}</span>}{disabled && <span className="ml-auto rounded-full bg-[#ece8e1] px-1.5 py-0.5 text-[10px] tracking-wide text-[#8a8578]">Soon</span>}</button> })}</nav></div><div className="hidden border-t border-[#e5e0d8] p-5 md:block"><p className="flex items-center gap-2 text-[11px] font-medium text-[#8a8578]"><ShieldCheck className="size-4"/> Audit Logged • CJIS Compliant</p></div></aside>
}
