// Nexus_Intel/src/graph/case1140.js
// Case: THE 11:40 MURDER (CAS-2026-1140)
// Cast: Hriday (Victim), Akshay Kumar Singh (Murderer), Shreyansh Agrawal (Uninvolved),
//       Thaniska (Uninvolved), Swastik (Uninvolved), Devishi (Supporter/Accomplice).

export const case1140VictimTree = {
  id: 'v-hriday',
  label: 'Hriday',
  kind: 'root',
  side: 'victim',
  avatar: '/avatars/hriday.jpg',
  fields: [
    ['Full Legal Identity', 'Hriday V. Mehta (Age 32)'],
    ['Occupation / Company', 'Founder & Managing Director, Apex Trade Partners LLP'],
    ['Legal Status', 'Deceased • Homicide Victim'],
    ['Incident Window', '14 Aug 2026 • 21:05 to 21:18 IST'],
    ['Body Discovery', '14 Aug 2026 • 23:40 IST inside Warehouse Bay 3'],
    ['Autopsy Finding', 'Fatal trauma inflicted with W87 tactical folding knife; absence of defensive wounds indicating unexpected assault.'],
    ['Murder Weapon Match', 'Recovered tactical knife (EX-W87) confirmed positive for victim DNA spatter on blade.'],
    ['Audit Discrepancy', 'Discovered ₹32,50,000 siphoned from company reserves via 4 unauthorized tranches.'],
    ['Cell Telemetry', 'Dual-SIM handset latched to Dock Road Cell Tower at 21:03 IST; device stolen post-mortem.'],
  ],
  children: [
    {
      id: 'v-comms',
      label: 'Communications',
      kind: 'category',
      side: 'victim',
      fields: [
        ['Pre-Crime Outbound Calls', '2 recorded calls prior to warehouse arrival'],
        ['19:30 IST Target', 'Shreyansh Agrawal (Company Accountant)'],
        ['20:00 IST Target', 'Thaniska (Personal Confidante)'],
        ['Post-Mortem Transmission', '22:10 IST forged SMS to Shreyansh Agrawal'],
      ],
      children: [
        {
          id: 'v-shreyansh',
          label: 'Shreyansh Agrawal',
          kind: 'leaf',
          side: 'victim',
          avatar: '/avatars/shreyansh.jpg',
          fields: [
            ['Role & Relationship', 'Company Accountant (Uninvolved)'],
            ['Outbound Call Received', '14 Aug • 19:30 IST (Duration: 4m 12s)'],
            ['Call Transcript Excerpt', '"Shreyansh, pull the Q2 audit trails right now. I\'ve found where the missing money went. I know who did it."'],
            ['Accountant Response', 'Asked for identity to freeze banking tokens; Hriday declined, stating he would confront the culprit tonight.'],
            ['Post-Mortem Text Received', '14 Aug • 22:10 IST: "Everything is fine. I\'ll explain tomorrow."'],
            ['Alibi Verification', 'Confirmed at accounting office until 20:15 IST, arrived home at 20:45 IST; verified by CCTV and ISP logs.'],
            ['Status', 'Fully Exonerated • Key Prosecution Witness'],
          ],
          children: [],
        },
        {
          id: 'v-thaniska',
          label: 'Thaniska',
          kind: 'leaf',
          side: 'victim',
          avatar: '/avatars/thaniska.jpg',
          fields: [
            ['Role & Relationship', 'Close Friend of Hriday (Uninvolved)'],
            ['Outbound Call Received', '14 Aug • 20:00 IST (Duration: 3m 50s)'],
            ['Call Transcript Excerpt', '"Thaniska, I\'m heading to the warehouse now. If something happens to me tonight, check what I told Shreyansh."'],
            ['Friend Response', 'Urged Hriday to avoid going alone and inform law enforcement; Hriday dismissed caution as partnership friction.'],
            ['Alibi Verification', 'Home Wi-Fi router connection uninterrupted 19:10–02:00 IST; food delivery timestamped 20:40 IST (14km away).'],
            ['Status', 'Fully Exonerated • Investigative Warning Witness'],
          ],
          children: [],
        },
      ],
    },
    {
      id: 'v-financial',
      label: 'Financial Audit',
      kind: 'category',
      side: 'victim',
      fields: [
        ['Audited Account', 'HDFC Bank Current Account #9021884102'],
        ['Total Deficit', '₹32,50,000 across 4 unauthorized wire disbursements'],
        ['Auditor Sign-Off', 'Shreyansh Agrawal verified balance sheet reconciliation'],
        ['Signatory Access', 'Legacy co-founder credentials retained by Akshay Kumar Singh'],
        ['Audit Consequence', 'Scheduled in-person confrontation at Dock Road Warehouse at 21:05 IST'],
      ],
      children: [],
    },
    {
      id: 'v-timeline',
      label: 'Crime Timeline',
      kind: 'category',
      side: 'victim',
      fields: [
        ['19:30 IST', 'Hriday calls Shreyansh Agrawal disclosing fraud discovery'],
        ['20:00 IST', 'Hriday calls Thaniska with premonition warning message'],
        ['21:05 IST', 'Hriday arrives at the Dock Road Warehouse'],
        ['21:05 - 21:18 IST', 'Heated confrontation with Akshay Kumar Singh regarding stolen funds'],
        ['21:18 IST', 'Fatal blunt-force trauma inflicted by Akshay Kumar Singh'],
        ['23:40 IST', 'Body discovered inside warehouse by night patrol'],
      ],
      children: [],
    },
    {
      id: 'v-spoof',
      label: 'Post-Mortem Spoof',
      kind: 'category',
      side: 'victim',
      fields: [
        ['Transmission Time', '14 Aug • 22:10 IST (52 mins after victim death)'],
        ['Transmitting Device', 'Hriday\'s personal handset (IMEI 358941029411048)'],
        ['Recipient Number', 'Shreyansh Agrawal (+91 98201-11840)'],
        ['Message Content', '"Everything is fine. I\'ll explain tomorrow."'],
        ['Digital Forensic Fact', 'Tower handoff confirms transmission originated along Dock Road corridor while Akshay was departing scene.'],
      ],
      children: [],
    },
  ],
}

export const case1140SuspectTree = {
  id: 's-akshay',
  label: 'Akshay Kumar Singh',
  kind: 'root',
  side: 'suspect',
  avatar: '/avatars/akshay.jpg',
  fields: [
    ['Full Legal Identity', 'Akshay Kumar Singh (Age 34)'],
    ['Former Relationship', 'Former Co-Founder & Business Partner with Hriday'],
    ['Motive', 'Embezzlement exposure; faced personal debts of ₹40,00,000'],
    ['Crime Scene Window', 'Dock Road Warehouse • 20:45 to 21:45 IST (60 mins total)'],
    ['Arrival at Scene', '20:45 IST (dropped off by Swastik)'],
    ['Lethal Encounter', '21:18 IST (fatal blunt-force trauma to victim cranium)'],
    ['Cover-Up Panic Call', '21:27 IST (called Devishi to orchestrate alibi)'],
    ['Departure from Scene', '21:45 IST on foot; device spoofed victim text at 22:10 IST'],
    ['Physical Weapon', 'Folding tactical knife engraved "W87" recovered in perimeter trench; victim DNA identified.'],
    ['Forensic Evidence', 'Blood spatter matching Hriday DNA recovered on right dress shoe; victim phone seized nearby.'],
    ['Risk Rating', 'Critical (Homicide & Evidence Tampering)'],
  ],
  children: [
    {
      id: 's-transport',
      label: 'Transportation',
      kind: 'category',
      side: 'suspect',
      fields: [
        ['Pre-Crime Transit Call', '14 Aug • 20:20 IST to Swastik'],
        ['Transit Vehicle', 'Silver Honda City (MH-02-CD-4190)'],
        ['Drop-Off Point', 'Dock Road Warehouse perimeter at 20:45 IST'],
        ['Driver Disposition', 'Swastik departed immediately at 20:45 IST; completely cleared'],
      ],
      children: [
        {
          id: 's-swastik',
          label: 'Swastik',
          kind: 'leaf',
          side: 'suspect',
          avatar: '/avatars/swastik.jpg',
          fields: [
            ['Role & Relationship', 'Friend of Akshay / Unwitting Driver (False Lead)'],
            ['Transit Call Timestamp', '14 Aug • 20:20 IST (Akshay requested urgent lift)'],
            ['Vehicle Data', 'Honda City (MH-02-CD-4190); in-car dashcam and GPS logs verified.'],
            ['Drop-Off Timestamp', '14 Aug • 20:45 IST at Dock Road Warehouse perimeter'],
            ['Departure Timestamp', '14 Aug • 20:46 IST (immediate departure upon drop-off)'],
            ['Toll Plaza Verification', 'Bandra-Worli Toll Plaza FastTag scan at 21:02 IST (18km away)'],
            ['Temporal Exoneration', 'Departed 33 mins prior to the 21:18 IST murder; no physical involvement.'],
            ['Status', 'Exonerated • False Positive Cleared by Chrono-Telemetry'],
          ],
          children: [],
        },
      ],
    },
    {
      id: 's-accomplice',
      label: 'Alibi & Cover-Up',
      kind: 'category',
      side: 'suspect',
      fields: [
        ['Co-Conspirator', 'Devishi (Close confidante of Akshay)'],
        ['Incoming Confession Call', '21:27 IST (lasting 3 mins 42 secs)'],
        ['Alibi Fabrication Start', '21:45 IST (scripted SMS thread at Bistro 9)'],
        ['Conspiracy Crime', 'Active evidence tampering and fraudulent joint alibi creation'],
      ],
      children: [
        {
          id: 's-devishi',
          label: 'Devishi',
          kind: 'leaf',
          side: 'suspect',
          fields: [
            ['Role & Relationship', 'Close Friend / Accomplice to Akshay Kumar Singh'],
            ['Panic Call Received', '14 Aug • 21:27 IST (Akshay reported the fatal encounter)'],
            ['Cover-Up Agreement', 'Agreed to manufacture false alibi claiming joint dinner at Bistro 9.'],
            ['Fabricated SMS Thread', '21:45: "Table is ready at Bistro 9" • 21:48: "Just parking outside" • 21:52: "Ordered food."'],
            ['Forensic Contradiction', 'Cell tower logs prove Akshay was still 12km away on Dock Road at 21:48 IST, completely puncturing the alibi.'],
            ['Legal Classification', 'Criminal Conspiracy & Evidence Tampering (High Suspicion)'],
            ['Risk Rating', 'High • Active Accomplice'],
          ],
          children: [],
        },
      ],
    },
    {
      id: 's-motive',
      label: 'Financial Theft',
      kind: 'category',
      side: 'suspect',
      fields: [
        ['Embezzlement Amount', '₹32,50,000 from Apex Trade Partners LLP reserves'],
        ['Modus Operandi', 'Leveraged unrevoked signatory credentials on current account'],
        ['Personal Debt', 'Accumulated ₹40,00,000 in speculative trading losses'],
        ['Dispute Escalation', 'Murdered Hriday to permanently suppress audit revelation'],
      ],
      children: [],
    },
    {
      id: 's-timeline',
      label: 'Suspect Timeline',
      kind: 'category',
      side: 'suspect',
      fields: [
        ['20:20 IST', 'Calls Swastik requesting emergency lift to warehouse'],
        ['20:45 IST', 'Arrives at Dock Road Warehouse; Swastik departs immediately'],
        ['21:05 IST', 'Hriday arrives; violent confrontation begins over missing funds'],
        ['21:18 IST', 'Inflicts fatal wound with W87 tactical knife; murders Hriday'],
        ['21:27 IST', 'Places 3m 42s confession/panic call to Devishi'],
        ['21:45 IST', 'Departs warehouse on foot; discards murder weapon in drainage trench'],
        ['22:10 IST', 'Uses Hriday\'s stolen handset to send spoof text to Shreyansh Agrawal'],
      ],
      children: [],
    },
    {
      id: 's-evidence',
      label: 'Physical Evidence',
      kind: 'category',
      side: 'suspect',
      fields: [
        ['Primary Murder Weapon', 'Tactical folding knife engraved "W87" with spider motif on stainless handle'],
        ['Ballistics & Serology', 'Blood micro-spatter on blade matches victim Hriday V. Mehta DNA (99.98%)'],
        ['Latent Dactyloscopy', 'Right thumb and index print on bolster matches Akshay Kumar Singh'],
        ['Recovery Location', 'Storm drain grate 120m south of Dock Road Warehouse (recovered 15 Aug 06:15 IST)'],
      ],
      children: [
        {
          id: 's-weapon-w87',
          label: 'Knife (W87)',
          kind: 'leaf',
          side: 'suspect',
          avatar: '/evidence/knife_w87_thumb.jpg',
          evidenceImage: '/evidence/knife_w87.jpg',
          fields: [
            ['Exhibit ID', 'EX-2026-W87 // Murder Weapon'],
            ['Weapon Type', 'Tactical folding pocket knife with black-coated blade'],
            ['Laser Engraving', '"W87" stamped on main blade bevel'],
            ['Handle Design', 'Relief carved spider and web on stainless steel frame'],
            ['DNA Serology Match', 'Blood residue on blade edge matches victim Hriday V. Mehta'],
            ['Fingerprint Match', 'Latent friction ridges on bolster match Akshay Kumar Singh'],
            ['Recovery Site', 'Drainage trench 120m south of Dock Road Warehouse'],
            ['Status', 'Secured in Central Forensic Science Laboratory (CFSL)']
          ],
          children: [],
        },
      ],
    },
  ],
}

export const case1140RootLinkEdge = {
  id: 'e-1140-homicide',
  source: 'v-hriday',
  target: 's-akshay',
  label: 'Confrontation & Murder (21:18 IST)',
}

export const case1140CrossEdges = [
  {
    id: 'e-1140-transit',
    source: 's-transport',
    target: 's-swastik',
    label: 'Ride Drop-Off 20:45 (Departed 33m Pre-Murder)',
  },
  {
    id: 'e-1140-alibi',
    source: 's-akshay',
    target: 's-devishi',
    label: 'Panic Call 21:27 & Staged Alibi 21:45',
  },
  {
    id: 'e-1140-shreyansh-call',
    source: 'v-hriday',
    target: 'v-shreyansh',
    label: 'Fraud Disclosure Call 19:30',
  },
  {
    id: 'e-1140-thaniska-call',
    source: 'v-hriday',
    target: 'v-thaniska',
    label: 'Warning Premonition Call 20:00',
  },
  {
    id: 'e-1140-spoof-msg',
    source: 's-akshay',
    target: 'v-spoof',
    label: 'Post-Mortem Spoofed SMS 22:10',
  },
  {
    id: 'e-1140-motive-link',
    source: 'v-financial',
    target: 's-motive',
    label: '₹32.5L Embezzlement Audit Nexus',
  },
  {
    id: 'e-1140-weapon-link',
    source: 's-weapon-w87',
    target: 'v-hriday',
    label: 'Lethal Murder Weapon Match (EX-W87)',
  },
]

export const CASE_1140_NARRATIVE = {
  title: 'Case 11:40 — The Warehouse Murder',
  victim: 'Hriday',
  perpetrator: 'Akshay Kumar Singh',
  incidentDate: '14 August 2026',
  discoveryTime: '23:40 IST',
  location: 'Abandoned Warehouse, Industrial Dock Road',
  cast: [
    { name: 'Hriday', avatar: '/avatars/hriday.jpg', role: 'Victim', status: 'Deceased (Murdered 21:18 IST)', note: 'Business owner who uncovered systematic ₹32.5L theft and confronted his former partner at the warehouse.' },
    { name: 'Akshay Kumar Singh', avatar: '/avatars/akshay.jpg', role: 'Murderer', status: 'Prime Suspect', note: 'Former business partner who embezzled funds, committed fatal assault at 21:18 IST, and forged an alibi.' },
    { name: 'Shreyansh Agrawal', avatar: '/avatars/shreyansh.jpg', role: 'Company Accountant (Uninvolved)', status: 'Exonerated', note: 'Accountant who audited accounts; received 19:30 disclosure call and 22:10 post-mortem text.' },
    { name: 'Thaniska', avatar: '/avatars/thaniska.jpg', role: 'Close Friend (Uninvolved)', status: 'Exonerated', note: 'Received 20:00 warning call; verified at home 14km away during the entire incident window.' },
    { name: 'Swastik', avatar: '/avatars/swastik.jpg', role: 'Transit Driver (False Lead)', status: 'Exonerated (GPS Cleared)', note: 'Gave Akshay a ride, dropped him off at 20:45 IST, and departed 33 minutes before the lethal encounter.' },
    { name: 'Devishi', avatar: null, role: 'Supporter / Accomplice', status: 'High Suspicion (Conspiracy)', note: 'Received 21:27 post-murder call; engineered false Bistro 9 alibi text thread at 21:45 IST.' },
  ],
  timeline: [
    { time: '19:30 IST', event: 'Hriday calls Shreyansh Agrawal disclosing fraud discovery: "I\'ve found where the missing money went. I know who did it."' },
    { time: '20:00 IST', event: 'Hriday calls Thaniska with premonition warning: "If something happens to me tonight, check what I told Shreyansh."' },
    { time: '20:20 IST', event: 'Akshay calls Swastik asking for an urgent ride near the Dock Road warehouse.' },
    { time: '20:45 IST', event: 'Swastik drops Akshay at warehouse perimeter and departs immediately (verified by FastTag at 21:02).' },
    { time: '21:05 IST', event: 'Hriday arrives at warehouse; heated confrontation begins over ₹32.5L stolen funds.' },
    { time: '21:18 IST', event: 'Argument turns violent; Akshay murders Hriday with fatal cranial trauma.' },
    { time: '21:27 IST', event: 'Akshay places 3m 42s panic call to Devishi; Devishi agrees to fabricate false joint alibi.' },
    { time: '21:45 IST', event: 'Akshay departs warehouse; Devishi begins firing scripted SMS thread claiming dinner at Bistro 9.' },
    { time: '22:10 IST', event: 'Shreyansh receives SMS from Hriday\'s phone: "Everything is fine. I\'ll explain tomorrow." (Sent 52 mins post-mortem).' },
    { time: '23:40 IST', event: 'Hriday\'s body is discovered inside the abandoned warehouse.' },
  ],
}
